import type { Exercise, Program, Document, Patient, ChartSession, Notification, Physio, Employee, Clinic, ClinicLocation } from './types';

export const mockPhysio: Physio = {
  id: 'p1',
  firstName: 'Sarah',
  lastName: 'Harper',
  email: 'sarah.harper@reaclinic.com',
  phone: '(604) 555-0100',
  clinicName: 'Rea Pelvic Health',
  credentials: 'PT, DPT, PRPC',
  title: 'Clinic Owner & Director',
  bio: 'Dr. Sarah Harper is a pelvic floor physiotherapist with over 15 years of clinical experience specializing in pelvic health across all life stages. She founded Rea Pelvic Health in 2018 with a mission to make evidence-based pelvic floor care accessible and empowering for every patient.',
  avatarInitials: 'SH',
  role: 'owner',
  clinicId: 'clinic1',
  locationId: 'loc1',
};

export const mockClinic: Clinic = {
  id: 'clinic1',
  name: 'Rea Pelvic Health',
  address: '1420 Health Sciences Drive, Suite 300, Vancouver, BC V6T 1Z3',
  phone: '(604) 555-0100',
  email: 'info@reapelvichealth.com',
  website: 'www.reapelvichealth.com',
  description: 'Rea Pelvic Health is a specialized physiotherapy clinic focused on pelvic floor rehabilitation for women across all life stages — from postpartum recovery to menopause and beyond. Our multidisciplinary team delivers individualized, evidence-based care in a supportive and discreet environment.',
  logoInitials: 'RP',
};

export const mockClinicLocations: ClinicLocation[] = [
  {
    id: 'loc1',
    orgId: 'clinic1',
    name: 'Vancouver Clinic',
    city: 'Vancouver',
    regionCountry: 'BC, Canada',
    address: '1420 Health Sciences Drive, Suite 300, Vancouver, BC V6T 1Z3',
    phone: '(604) 555-0100',
    email: 'vancouver@reapelvichealth.com',
    description: "Rea Pelvic Health's founding clinic, established in 2018 in Vancouver, BC. Located in one of Canada's most health-forward cities, the Vancouver clinic brings together a multidisciplinary team of pelvic floor physiotherapists serving the Lower Mainland and beyond. Vancouver's deep commitment to active living, wellness, and progressive healthcare made it the natural home for Rea's mission — delivering evidence-based, patient-centred pelvic floor care in a supportive and discreet environment.",
    employeeIds: ['emp1', 'emp2', 'emp_van3'],
  },
  {
    id: 'loc2',
    orgId: 'clinic1',
    name: 'New York City Clinic',
    city: 'New York City',
    regionCountry: 'NY, USA',
    address: '245 W 17th St, Suite 800, New York, NY 10011',
    phone: '(212) 555-0188',
    email: 'nyc@reapelvichealth.com',
    description: "Rea Pelvic Health's first American location, bringing our evidence-based pelvic floor care to New York City. In one of the world's most fast-paced and demanding cities, our NYC clinic provides a calm, expert, and discreet environment for pelvic health treatment. New York's extraordinary diversity and high demand for specialized, integrative healthcare made it the ideal setting to extend Rea's mission — offering individualized care to patients across the boroughs and the broader tri-state area.",
    employeeIds: ['emp3', 'emp4', 'emp_nyc3'],
  },
  {
    id: 'loc3',
    orgId: 'clinic1',
    name: 'Utrecht Clinic',
    city: 'Utrecht',
    regionCountry: 'Netherlands',
    address: 'Catharijnesingel 48, 3511 GC Utrecht, Netherlands',
    phone: '+31 30 555 0122',
    email: 'utrecht@reapelvichealth.com',
    description: "Rea Pelvic Health's European hub, located in the heart of Utrecht, Netherlands. Utrecht's exceptional academic and medical culture — home to one of Europe's leading university medical centres — made it a natural choice for Rea's international expansion. The clinic serves patients from across the Netherlands and neighbouring European countries, combining Rea's Canadian clinical expertise with the progressive, research-driven approach to pelvic health that the Netherlands is internationally recognized for.",
    employeeIds: ['emp_uth1', 'emp_uth2', 'emp_uth3'],
  },
];

export const mockEmployees: Employee[] = [
  // ── Vancouver (loc1) ──
  {
    id: 'emp1',
    firstName: 'Emily',
    lastName: 'Chen',
    email: 'emily.chen@reaclinic.com',
    phone: '(604) 555-0121',
    credentials: 'PT, DPT',
    title: 'Clinic Lead & Physiotherapist',
    bio: 'Emily Chen specializes in postpartum pelvic floor rehabilitation and incontinence management. She completed her Doctor of Physical Therapy at UBC and holds advanced certifications in women\'s health physiotherapy. Emily leads the Vancouver clinic team.',
    role: 'admin',
    avatarInitials: 'EC',
    patientIds: ['pat1', 'pat2'],
    clinicId: 'clinic1',
    joinedAt: '2024-03-15',
    specialties: ['Postpartum Recovery', 'Incontinence', 'Pelvic Pain'],
    archived: false,
  },
  {
    id: 'emp2',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@reaclinic.com',
    phone: '(604) 555-0134',
    credentials: 'MSc PT, CAFCI',
    title: 'Senior Physiotherapist',
    bio: 'James Wilson brings over 10 years of experience in pelvic health physiotherapy, with particular expertise in pelvic organ prolapse and post-surgical rehabilitation. He completed his MSc in Physical Therapy at Queen\'s University.',
    role: 'staff',
    avatarInitials: 'JW',
    patientIds: ['pat3', 'pat4', 'pat_van5', 'pat_van6'],
    clinicId: 'clinic1',
    joinedAt: '2023-09-01',
    specialties: ['Prolapse', 'Post-Surgical Rehab', 'Pelvic Pain'],
    archived: false,
  },
  {
    id: 'emp_van3',
    firstName: 'Sophie',
    lastName: 'Kim',
    email: 'sophie.kim@reaclinic.com',
    phone: '(604) 555-0167',
    credentials: 'BScPT, MSc',
    title: 'Physiotherapist',
    bio: 'Sophie Kim joined Rea Pelvic Health Vancouver after completing her MSc in Physiotherapy at UBC. She has a special interest in pelvic floor rehabilitation for athletes and active individuals, combining her background in sport science with evidence-based pelvic health care.',
    role: 'staff',
    avatarInitials: 'SK',
    patientIds: ['pat_van7', 'pat_van8', 'pat_van9', 'pat8'],
    clinicId: 'clinic1',
    joinedAt: '2025-09-01',
    specialties: ['Athletic Rehab', 'Postpartum Recovery', 'Pelvic Pain'],
    archived: false,
  },
  // ── New York City (loc2) ──
  {
    id: 'emp3',
    firstName: 'Rachel',
    lastName: 'Torres',
    email: 'rachel.torres@reaclinic.com',
    phone: '(212) 555-0156',
    credentials: 'PT, CAFCI',
    title: 'Clinic Lead & Physiotherapist',
    bio: 'Rachel Torres leads Rea\'s New York City clinic, bringing expertise in menopause-related pelvic floor changes and incontinence management. She completed her BScPT at McMaster University and has pursued advanced training in pelvic health and dry needling. Rachel built the NYC team from the ground up.',
    role: 'admin',
    avatarInitials: 'RT',
    patientIds: ['pat5', 'pat6'],
    clinicId: 'clinic1',
    joinedAt: '2025-01-10',
    specialties: ['Menopause', 'Incontinence', 'Hip & Spine'],
    archived: false,
  },
  {
    id: 'emp4',
    firstName: 'Marcus',
    lastName: 'Laine',
    email: 'marcus.laine@reaclinic.com',
    phone: '(212) 555-0178',
    credentials: 'BScPT',
    title: 'Physiotherapist',
    bio: 'Marcus Laine relocated from Vancouver to join the NYC team at Rea Pelvic Health. He has a special interest in postpartum athletic recovery and exercise programming for pelvic health, and is known for his collaborative, goal-oriented approach.',
    role: 'staff',
    avatarInitials: 'ML',
    patientIds: ['pat_nyc3', 'pat_nyc4', 'pat_nyc5', 'pat_nyc6'],
    clinicId: 'clinic1',
    joinedAt: '2025-06-20',
    specialties: ['Postpartum Recovery', 'Athletic Rehab', 'Exercise Programming'],
    archived: false,
  },
  {
    id: 'emp_nyc3',
    firstName: 'Carlos',
    lastName: 'Rivera',
    email: 'carlos.rivera@reaclinic.com',
    phone: '(212) 555-0193',
    credentials: 'PT, DPT',
    title: 'Physiotherapist',
    bio: 'Carlos Rivera earned his DPT from Columbia University and has focused his career on pelvic floor rehabilitation, with a particular interest in chronic pelvic pain and post-surgical recovery. He brings a trauma-informed, whole-person approach to every patient interaction.',
    role: 'staff',
    avatarInitials: 'CR',
    patientIds: ['pat_nyc7', 'pat_nyc8', 'pat_nyc9', 'pat_nyc10'],
    clinicId: 'clinic1',
    joinedAt: '2025-08-15',
    specialties: ['Pelvic Pain', 'Post-Surgical Rehab', 'Incontinence'],
    archived: false,
  },
  // ── Utrecht (loc3) ──
  {
    id: 'emp_uth1',
    firstName: 'Lena',
    lastName: 'Fischer',
    email: 'lena.fischer@reaclinic.com',
    phone: '+31 30 555 0141',
    credentials: 'MSc PT',
    title: 'Clinic Lead & Physiotherapist',
    bio: 'Lena Fischer leads Rea\'s Utrecht clinic and brings deep expertise in prolapse management and menopause-related pelvic floor changes. She trained at Utrecht University and completed a fellowship in urogynaecological physiotherapy at UMC Utrecht. Lena is fluent in Dutch, German, and English.',
    role: 'admin',
    avatarInitials: 'LF',
    patientIds: ['pat_uth1', 'pat_uth2'],
    clinicId: 'clinic1',
    joinedAt: '2025-10-01',
    specialties: ['Prolapse', 'Menopause', 'Urogynaecology'],
    archived: false,
  },
  {
    id: 'emp_uth2',
    firstName: 'Pieter',
    lastName: 'van Dijk',
    email: 'pieter.vandijk@reaclinic.com',
    phone: '+31 30 555 0152',
    credentials: 'MSc PT, BIG',
    title: 'Physiotherapist',
    bio: 'Pieter van Dijk is a pelvic health physiotherapist trained at Amsterdam University of Applied Sciences. He specialises in postpartum pelvic floor rehabilitation and incontinence, and is one of the few male pelvic floor specialists in the Netherlands. Pieter is registered with the Dutch BIG register.',
    role: 'staff',
    avatarInitials: 'PD',
    patientIds: ['pat_uth3', 'pat_uth4', 'pat_uth5', 'pat_uth6'],
    clinicId: 'clinic1',
    joinedAt: '2025-10-01',
    specialties: ['Postpartum Recovery', 'Incontinence', 'Pelvic Pain'],
    archived: false,
  },
  {
    id: 'emp_uth3',
    firstName: 'Yasmine',
    lastName: 'Hamid',
    email: 'yasmine.hamid@reaclinic.com',
    phone: '+31 30 555 0163',
    credentials: 'BScPT',
    title: 'Physiotherapist',
    bio: 'Yasmine Hamid graduated from HAN University of Applied Sciences and joined Rea\'s Utrecht team at its founding. She has a strong background in pelvic floor rehabilitation for women across all life stages, with particular expertise in incontinence and pelvic pain in multicultural populations.',
    role: 'staff',
    avatarInitials: 'YH',
    patientIds: ['pat_uth7', 'pat_uth8', 'pat_uth9', 'pat_uth10'],
    clinicId: 'clinic1',
    joinedAt: '2025-10-01',
    specialties: ['Incontinence', 'Pelvic Pain', 'Women\'s Health'],
    archived: false,
  },
  // ── Archived ──
  {
    id: 'emp5',
    firstName: 'Olivia',
    lastName: 'Park',
    email: 'olivia.park@reaclinic.com',
    phone: '(604) 555-0199',
    credentials: 'PT, MSc',
    title: 'Physiotherapist',
    bio: 'Olivia Park worked at Rea Pelvic Health from 2022 to 2024, specializing in post-surgical pelvic floor rehabilitation. She has since relocated to pursue a research fellowship.',
    role: 'staff',
    avatarInitials: 'OP',
    patientIds: [],
    clinicId: 'clinic1',
    joinedAt: '2022-05-01',
    specialties: ['Post-Surgical Rehab', 'Pelvic Pain'],
    archived: true,
  },
];

export const mockExercises: Exercise[] = [
  {
    id: 'ex1',
    name: 'Diaphragmatic Breathing',
    description: 'Deep belly breathing to activate the diaphragm and coordinate pelvic floor relaxation.',
    instructions: [
      'Lie on your back with knees bent, feet flat.',
      'Place one hand on your chest and one on your belly.',
      'Inhale slowly through your nose, letting your belly rise.',
      'Exhale through pursed lips, feeling your belly fall.',
      'Repeat for the prescribed number of breaths.',
    ],
    commonMistakes: [
      'Breathing only into the chest rather than the belly.',
      'Holding breath between inhalation and exhalation.',
      'Tensing the shoulders during the breath.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Pelvic Pain', 'Incontinence', 'Postpartum'], surgery: [], muscle: ['Diaphragm', 'Pelvic Floor'], bodyPart: ['Pelvis', 'Core'] },
    defaultSets: 1, defaultReps: 10, defaultHoldSecs: 0, defaultFrequency: 'Daily',
    videoUrl: 'JFJtUtKQCuM',
    isFavorite: true, usageCount: 48, createdAt: '2026-01-10',
  },
  {
    id: 'ex2',
    name: 'Kegel – Quick Flick',
    description: 'Rapid pelvic floor contractions to improve fast-twitch muscle response.',
    instructions: [
      'Sit or lie in a comfortable position.',
      'Quickly contract the pelvic floor muscles as if stopping urine flow.',
      'Immediately release fully.',
      'Repeat the quick contractions at a steady pace.',
    ],
    commonMistakes: [
      'Not fully releasing between contractions.',
      'Contracting the gluteal or thigh muscles instead.',
      'Holding breath during the exercise.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Incontinence', 'Urgency'], surgery: [], muscle: ['Levator Ani', 'Coccygeus'], bodyPart: ['Pelvis'] },
    defaultSets: 3, defaultReps: 10, defaultHoldSecs: 1, defaultFrequency: 'Daily',
    videoUrl: 'ywMJe0un8bE',
    isFavorite: true, usageCount: 62, createdAt: '2026-01-10',
  },
  {
    id: 'ex3',
    name: 'Kegel – Sustained Hold',
    description: 'Prolonged pelvic floor contraction to build endurance in slow-twitch fibers.',
    instructions: [
      'Find a comfortable seated or lying position.',
      'Contract the pelvic floor muscles and lift upward.',
      'Hold the contraction for the prescribed duration.',
      'Release fully and rest for an equal amount of time.',
    ],
    commonMistakes: [
      'Gripping buttocks or inner thighs.',
      'Forgetting to fully relax after each contraction.',
      'Not lifting the pelvic floor — only squeezing outward.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Incontinence', 'Prolapse'], surgery: ['Post-Hysterectomy'], muscle: ['Levator Ani', 'Coccygeus'], bodyPart: ['Pelvis'] },
    defaultSets: 3, defaultReps: 8, defaultHoldSecs: 10, defaultFrequency: 'Daily',
    isFavorite: true, usageCount: 55, createdAt: '2026-01-10',
  },
  {
    id: 'ex4',
    name: 'Hip Bridge',
    description: 'Glute and core activation exercise that supports pelvic stability.',
    instructions: [
      'Lie on your back, knees bent, feet hip-width apart.',
      'Press feet into the floor and lift hips toward the ceiling.',
      'Squeeze glutes at the top, maintaining a neutral spine.',
      'Slowly lower hips back to the starting position.',
    ],
    commonMistakes: [
      'Overextending the lower back at the top.',
      'Feet too far from or too close to hips.',
      'Pushing through the toes instead of heels.',
    ],
    tags: { specialty: ['Pelvic Floor', 'Orthopedic'], condition: ['Pelvic Pain', 'Prolapse', 'Postpartum'], surgery: ['Post-THA', 'Post-TKA'], muscle: ['Glutes', 'Transverse Abdominis', 'Pelvic Floor'], bodyPart: ['Pelvis', 'Hip', 'Core'] },
    defaultSets: 3, defaultReps: 12, defaultHoldSecs: 3, defaultFrequency: 'Daily',
    isFavorite: true, usageCount: 41, createdAt: '2026-01-15',
  },
  {
    id: 'ex5',
    name: 'Pelvic Tilt',
    description: 'Gentle lumbar mobilization that coordinates pelvic floor and core activation.',
    instructions: [
      'Lie on your back with knees bent.',
      'Gently flatten your lower back against the floor by tilting your pelvis.',
      'Hold briefly, then release to neutral.',
      'Progress to rocking forward and back smoothly.',
    ],
    commonMistakes: [
      'Moving from the hips rather than the lumbar spine.',
      'Holding breath throughout the movement.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Pelvic Pain', 'Postpartum'], surgery: ['C-Section'], muscle: ['Transverse Abdominis', 'Multifidus'], bodyPart: ['Pelvis', 'Spine', 'Core'] },
    defaultSets: 2, defaultReps: 15, defaultHoldSecs: 0, defaultFrequency: 'Daily',
    isFavorite: false, usageCount: 33, createdAt: '2026-01-15',
  },
  {
    id: 'ex6',
    name: 'Clamshell',
    description: 'Hip abductor strengthening to improve lateral pelvic stability.',
    instructions: [
      'Lie on your side with hips stacked, knees bent to 45°.',
      'Keeping feet together, lift the top knee toward the ceiling.',
      'Rotate from the hip — do not roll your pelvis backward.',
      'Lower with control and repeat.',
    ],
    commonMistakes: [
      'Rolling the pelvis backward to gain range.',
      'Lifting the foot along with the knee.',
    ],
    tags: { specialty: ['Pelvic Floor', 'Orthopedic'], condition: ['Pelvic Pain', 'Prolapse'], surgery: ['Post-THA'], muscle: ['Glutes', 'Hip Abductors'], bodyPart: ['Hip', 'Pelvis'] },
    defaultSets: 3, defaultReps: 15, defaultHoldSecs: 2, defaultFrequency: 'Daily',
    isFavorite: false, usageCount: 28, createdAt: '2026-01-20',
  },
  {
    id: 'ex7',
    name: 'Dead Bug',
    description: 'Anti-rotation core stability exercise with coordinated limb movement.',
    instructions: [
      'Lie on your back, arms straight toward ceiling, knees at 90° in tabletop.',
      'Exhale and press lower back into the floor.',
      'Slowly lower opposite arm and leg toward the floor.',
      'Return to start and alternate sides.',
    ],
    commonMistakes: [
      'Allowing lower back to lift off the floor.',
      'Moving too quickly through the motion.',
      'Forgetting to breathe — exhale on exertion.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Postpartum', 'Pelvic Pain'], surgery: ['C-Section'], muscle: ['Transverse Abdominis', 'Multifidus', 'Pelvic Floor'], bodyPart: ['Core', 'Spine'] },
    defaultSets: 3, defaultReps: 8, defaultHoldSecs: 0, defaultFrequency: 'Daily',
    isFavorite: false, usageCount: 19, createdAt: '2026-02-01',
  },
  {
    id: 'ex8',
    name: 'Squat – Bodyweight',
    description: 'Functional lower limb strengthening with integrated pelvic floor coordination.',
    instructions: [
      'Stand with feet shoulder-width apart, toes turned slightly out.',
      'Inhale and hinge at hips and knees simultaneously, lowering into squat.',
      'Keep chest up and knees tracking over toes.',
      'Exhale and engage pelvic floor as you press back to standing.',
    ],
    commonMistakes: [
      'Knees caving inward (valgus collapse).',
      'Heels lifting off the floor.',
      'Rounding the lower back at the bottom.',
    ],
    tags: { specialty: ['Pelvic Floor', 'Orthopedic'], condition: ['Incontinence', 'Prolapse'], surgery: ['Post-TKA', 'Post-THA'], muscle: ['Glutes', 'Quadriceps', 'Pelvic Floor'], bodyPart: ['Hip', 'Knee', 'Pelvis'] },
    defaultSets: 3, defaultReps: 10, defaultHoldSecs: 0, defaultFrequency: 'Every Other Day',
    isFavorite: false, usageCount: 22, createdAt: '2026-02-05',
  },
  {
    id: 'ex9',
    name: 'Cat-Cow Stretch',
    description: 'Spinal mobility and pelvic coordination exercise.',
    instructions: [
      'Start on hands and knees in a tabletop position.',
      'Inhale: drop belly, lift chest and tailbone (Cow).',
      'Exhale: round spine toward ceiling, tuck chin and pelvis (Cat).',
      'Flow smoothly between the two positions.',
    ],
    commonMistakes: [
      'Moving only from the neck rather than the whole spine.',
      'Locking elbows during the movement.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Pelvic Pain', 'Postpartum'], surgery: [], muscle: ['Multifidus', 'Pelvic Floor'], bodyPart: ['Spine', 'Pelvis'] },
    defaultSets: 1, defaultReps: 10, defaultHoldSecs: 0, defaultFrequency: 'Daily',
    isFavorite: true, usageCount: 36, createdAt: '2026-02-10',
  },
  {
    id: 'ex10',
    name: 'Sidelying Hip Flexion',
    description: 'Hip flexor strengthening in a gravity-reduced position.',
    instructions: [
      'Lie on your side, bottom leg straight, top leg straight.',
      'Flex the top hip to lift the leg to about 45°.',
      'Lower with control without resting on the bottom leg.',
    ],
    commonMistakes: [
      'Rotating the pelvis forward to compensate.',
      'Lifting higher than 45°.',
    ],
    tags: { specialty: ['Pelvic Floor', 'Orthopedic'], condition: ['Pelvic Pain'], surgery: ['Post-THA'], muscle: ['Hip Flexors', 'Pelvic Floor'], bodyPart: ['Hip', 'Pelvis'] },
    defaultSets: 3, defaultReps: 12, defaultHoldSecs: 0, defaultFrequency: 'Every Other Day',
    isFavorite: false, usageCount: 14, createdAt: '2026-02-15',
  },
  {
    id: 'ex11',
    name: 'Transverse Abdominis Activation',
    description: 'Isolated deep core activation — the foundation for pelvic support.',
    instructions: [
      'Lie on your back or sit tall.',
      'Gently draw your lower abdomen in and up, as if pulling belly button to spine.',
      'Hold without holding your breath.',
      'Maintain normal breathing throughout the hold.',
    ],
    commonMistakes: [
      'Bracing (using superficial abs) rather than drawing in.',
      'Holding breath during the contraction.',
      'Posteriorly tilting the pelvis to activate.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Prolapse', 'Postpartum', 'Incontinence'], surgery: ['C-Section', 'Post-Hysterectomy'], muscle: ['Transverse Abdominis', 'Pelvic Floor'], bodyPart: ['Core', 'Pelvis'] },
    defaultSets: 3, defaultReps: 10, defaultHoldSecs: 10, defaultFrequency: 'Daily',
    isFavorite: true, usageCount: 44, createdAt: '2026-01-10',
  },
  {
    id: 'ex12',
    name: 'Adductor Ball Squeeze',
    description: 'Inner thigh and pelvic floor co-activation using a small ball or pillow.',
    instructions: [
      'Sit at the edge of a chair with a ball or folded pillow between your knees.',
      'Gently squeeze the ball and simultaneously lift the pelvic floor.',
      'Hold, then release both simultaneously.',
    ],
    commonMistakes: [
      'Gripping only with inner thighs without engaging the pelvic floor.',
      'Leaning forward or backward in the chair.',
    ],
    tags: { specialty: ['Pelvic Floor'], condition: ['Incontinence', 'Prolapse'], surgery: [], muscle: ['Adductors', 'Levator Ani'], bodyPart: ['Pelvis', 'Hip'] },
    defaultSets: 3, defaultReps: 10, defaultHoldSecs: 5, defaultFrequency: 'Daily',
    isFavorite: false, usageCount: 17, createdAt: '2026-03-01',
  },
];

export const mockPrograms: Program[] = [
  {
    id: 'prog1',
    name: 'Postpartum Foundation',
    description: 'Gentle reactivation program for postpartum pelvic floor recovery.',
    exercises: [
      { exerciseId: 'ex1', sets: 1, reps: 10, holdSecs: 0, frequency: 'Daily', adherence: 85 },
      { exerciseId: 'ex11', sets: 3, reps: 10, holdSecs: 10, frequency: 'Daily', adherence: 72 },
      { exerciseId: 'ex3', sets: 3, reps: 8, holdSecs: 10, frequency: 'Daily', adherence: 68 },
      { exerciseId: 'ex5', sets: 2, reps: 15, holdSecs: 0, frequency: 'Daily', adherence: 90 },
    ],
    tags: ['Pelvic Floor', 'Postpartum', 'Beginner'],
    isFavorite: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'prog2',
    name: 'Incontinence Recovery',
    description: 'Targeted pelvic floor strengthening for stress and urge incontinence.',
    exercises: [
      { exerciseId: 'ex2', sets: 3, reps: 10, holdSecs: 1, frequency: 'Daily', adherence: 60 },
      { exerciseId: 'ex3', sets: 3, reps: 8, holdSecs: 10, frequency: 'Daily', adherence: 55 },
      { exerciseId: 'ex1', sets: 1, reps: 10, holdSecs: 0, frequency: 'Daily', adherence: 78 },
      { exerciseId: 'ex4', sets: 3, reps: 12, holdSecs: 3, frequency: 'Every Other Day', adherence: 45 },
    ],
    tags: ['Pelvic Floor', 'Incontinence', 'Intermediate'],
    isFavorite: true,
    createdAt: '2026-01-25',
  },
  {
    id: 'prog3',
    name: 'Pelvic Pain Relief',
    description: 'Relaxation-focused program for hypertonic pelvic floor and pelvic pain.',
    exercises: [
      { exerciseId: 'ex1', sets: 1, reps: 10, holdSecs: 0, frequency: 'Daily', adherence: 80 },
      { exerciseId: 'ex9', sets: 1, reps: 10, holdSecs: 0, frequency: 'Daily', adherence: 75 },
      { exerciseId: 'ex5', sets: 2, reps: 15, holdSecs: 0, frequency: 'Daily', adherence: 70 },
    ],
    tags: ['Pelvic Floor', 'Pelvic Pain', 'Relaxation'],
    isFavorite: false,
    createdAt: '2026-02-10',
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc1',
    name: 'Intake Form',
    isFavorite: true,
    isDefault: true,
    updatedAt: '2026-05-05',
    fields: [
      { id: 'f1', label: 'Date of Birth', type: 'date' },
      { id: 'f2', label: 'Chief Complaint', type: 'textarea' },
      { id: 'f3', label: 'Symptom Duration', type: 'text' },
      { id: 'f4', label: 'Previous Physiotherapy', type: 'checkbox' },
      { id: 'f5', label: 'Medications', type: 'textarea' },
      { id: 'f6', label: 'Relevant Medical History', type: 'textarea' },
      { id: 'f7', label: 'Goals for Treatment', type: 'textarea' },
    ],
  },
  {
    id: 'doc3',
    name: 'Credit Card Authorization',
    isFavorite: false,
    isDefault: true,
    updatedAt: '2026-05-05',
    fields: [
      { id: 'f1', label: 'Cardholder Name', type: 'text' },
      { id: 'f2', label: 'Card Type', type: 'dropdown', options: ['Visa', 'Mastercard', 'Amex', 'Discover'] },
      { id: 'f3', label: 'Authorization Amount', type: 'text' },
      { id: 'f4', label: 'I authorize the above amount to be charged', type: 'checkbox' },
      { id: 'f5', label: 'Signature Date', type: 'date' },
    ],
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'pat1',
    firstName: 'Margaret',
    lastName: 'Chen',
    email: 'margaret.chen@email.com',
    phone: '212-555-0101',
    address: '84 Riverside Dr, New York, NY 10024',
    location: 'Vancouver, BC',
    avatarInitials: 'MC',
    status: 'active',
    lastModified: '2026-05-22',
    programId: 'prog1',
    assignedEmployeeIds: ['emp1'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 12,
    clinicId: 'clinic1',
    metrics: { age: 34, sexAssignedAtBirth: 'Female', height: "5'5\"", weight: '142 lbs', handDominance: 'Right' },
    injuryHistory: {
      mechanism: 'Postpartum – vaginal delivery with 2nd degree tear',
      dateOfOnset: 'March 2026',
      surgeryType: 'N/A',
      surgeryDate: 'N/A',
      symptomEvolution: 'Patient reports increased urinary leakage with coughing and sneezing since delivery. Some pelvic heaviness noted.',
      functionalMobility: 'Independent with all ADLs. Returned to walking 30 min/day.',
      management: 'Pelvic floor physiotherapy initiated at 6 weeks postpartum.',
      homeEquipment: 'Yoga mat, resistance bands',
    },
    pmhx: { previousEpisode: 'N/A', pmhx: 'GDM during pregnancy (resolved)', previousTreatments: 'None for pelvic floor', medicationList: 'Prenatal vitamins', exams: 'Postpartum OB clearance May 2026' },
    sohx: { job: 'Graphic designer (WFH)', hobbies: 'Yoga, hiking', socialEnvironment: 'Lives with husband and newborn', physicalEnvironment: '3rd floor walkup', clientGoals: 'Return to yoga and running without leakage' },
    lifestyle: { otherConditions: 'None', diet: 'Well balanced', exercise: 'Yoga pre-pregnancy, walking currently', smoker: 'Non-smoker', alcohol: 'None currently (breastfeeding)' },
    medicalHistory: { otherConditions: 'GDM during pregnancy', attachments: [] },
    emergencyContact: { firstName: 'David', lastName: 'Chen', phone: '212-555-0102', email: 'david.chen@email.com', address: '84 Riverside Dr, New York, NY 10024', relationship: 'Spouse' },
    documents: [
      { documentId: 'doc1', submittedAt: '2026-04-10', fieldValues: { f1: '1991-08-15', f2: 'Urinary incontinence and pelvic heaviness postpartum', f3: '7 weeks', f4: 'No', f5: 'Prenatal vitamins', f6: 'GDM during pregnancy', f7: 'Return to exercise without symptoms' } },
      { documentId: 'doc2', submittedAt: '2026-04-10', fieldValues: { f1: 'Blue Cross Blue Shield', f2: '8847221', f3: 'MCH990', f4: 'Margaret Chen', f5: '1991-08-15', f6: 'Self' } },
    ],
  },
  {
    id: 'pat2',
    firstName: 'Karen',
    lastName: 'Oduya',
    email: 'karen.oduya@email.com',
    phone: '416-555-0203',
    address: '210 King St W, Toronto, ON M5H 1K7',
    location: 'Vancouver, BC',
    avatarInitials: 'KO',
    status: 'active',
    lastModified: '2026-05-20',
    programId: 'prog2',
    assignedEmployeeIds: ['emp1'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 8,
    clinicId: 'clinic1',
    metrics: { age: 52, sexAssignedAtBirth: 'Female', height: "5'3\"", weight: '168 lbs', handDominance: 'Right' },
    injuryHistory: {
      mechanism: 'Gradual onset stress urinary incontinence, worsened over 2 years',
      dateOfOnset: 'January 2024',
      surgeryType: 'N/A',
      surgeryDate: 'N/A',
      symptomEvolution: 'Leakage with coughing, sneezing, and jumping. Urgency episodes 3–4x/day. Night voiding 1–2x.',
      functionalMobility: 'Independent. Active lifestyle — tennis 2x/week.',
      management: 'Pelvic floor PT, bladder diary initiated.',
      homeEquipment: 'None',
    },
    pmhx: { previousEpisode: 'N/A', pmhx: 'Hypertension (controlled)', previousTreatments: 'None for pelvic floor', medicationList: 'Lisinopril 10mg daily', exams: 'Urodynamics Feb 2026 – confirmed mixed incontinence' },
    sohx: { job: 'High school principal', hobbies: 'Tennis, reading', socialEnvironment: 'Lives with husband, 2 adult children nearby', physicalEnvironment: '2-storey home, no barriers', clientGoals: 'Return to tennis without leakage; reduce urgency episodes' },
    lifestyle: { otherConditions: 'Hypertension', diet: 'Mediterranean style', exercise: 'Tennis 2x/wk, walking daily', smoker: 'Non-smoker', alcohol: 'Occasional, 1–2x/month' },
    medicalHistory: { otherConditions: 'Hypertension – well controlled', attachments: [] },
    emergencyContact: { firstName: 'James', lastName: 'Oduya', phone: '416-555-0204', email: 'james.oduya@email.com', address: '210 King St W, Toronto, ON M5H 1K7', relationship: 'Spouse' },
    documents: [
      { documentId: 'doc1', submittedAt: '2026-03-15', fieldValues: { f1: '1973-11-22', f2: 'Stress and urge urinary incontinence', f3: '2 years', f4: 'No', f5: 'Lisinopril 10mg', f6: 'Hypertension', f7: 'Play tennis confidently without leakage' } },
    ],
  },
  {
    id: 'pat3',
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya.nair@email.com',
    phone: '604-555-0305',
    address: '450 W Georgia St, Vancouver, BC V6B 1Z7',
    location: 'Vancouver, BC',
    avatarInitials: 'PN',
    status: 'active',
    lastModified: '2026-05-18',
    programId: 'prog3',
    assignedEmployeeIds: ['emp2'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 10,
    clinicId: 'clinic1',
    metrics: { age: 41, sexAssignedAtBirth: 'Female', height: "5'4\"", weight: '135 lbs', handDominance: 'Right' },
    injuryHistory: {
      mechanism: 'Chronic pelvic pain – onset following hysterectomy',
      dateOfOnset: 'September 2025',
      surgeryType: 'Laparoscopic hysterectomy (benign fibroid)',
      surgeryDate: 'August 2025',
      symptomEvolution: 'Deep pelvic aching, dyspareunia, difficulty sitting > 30 min. Symptoms stable but limiting.',
      functionalMobility: 'Independent. Avoids prolonged sitting and high-impact activity.',
      management: 'Post-surgical pelvic floor PT, manual therapy, pain education.',
      homeEquipment: 'Foam roller, heating pad',
    },
    pmhx: { previousEpisode: 'Endometriosis (diagnosed 2018, managed medically)', pmhx: 'Endometriosis, uterine fibroids', previousTreatments: 'Hormonal therapy, pain management', medicationList: 'Estradiol 0.5mg, Ibuprofen PRN', exams: 'Post-op pelvic ultrasound clear Nov 2025' },
    sohx: { job: 'Software engineer (remote)', hobbies: 'Pilates, cooking', socialEnvironment: 'Lives alone, partner nearby', physicalEnvironment: 'Condo, elevator building', clientGoals: 'Reduce pelvic pain, return to Pilates and intimacy' },
    lifestyle: { otherConditions: 'Endometriosis (history)', diet: 'Anti-inflammatory diet', exercise: 'Pilates pre-surgery, walking currently', smoker: 'Non-smoker', alcohol: 'Rarely' },
    medicalHistory: { otherConditions: 'Endometriosis (history), uterine fibroids (removed)', attachments: ['post-op-report.pdf'] },
    emergencyContact: { firstName: 'Anil', lastName: 'Nair', phone: '604-555-0306', email: 'anil.nair@email.com', address: '450 W Georgia St, Vancouver, BC', relationship: 'Parent' },
    documents: [
      { documentId: 'doc1', submittedAt: '2026-01-20', fieldValues: { f1: '1985-03-08', f2: 'Pelvic pain post-hysterectomy, dyspareunia', f3: '8 months', f4: 'No', f5: 'Estradiol 0.5mg, Ibuprofen PRN', f6: 'Endometriosis, hysterectomy', f7: 'Reduce pain, return to Pilates' } },
      { documentId: 'doc2', submittedAt: '2026-01-20', fieldValues: { f1: 'Sunlife Financial', f2: '334291', f3: 'PN8812', f4: 'Priya Nair', f5: '1985-03-08', f6: 'Self' } },
    ],
  },
  {
    id: 'pat4',
    firstName: 'Beth',
    lastName: 'Walters',
    email: 'beth.walters@email.com',
    phone: '312-555-0407',
    address: '1200 N Lake Shore Dr, Chicago, IL 60610',
    location: 'Vancouver, BC',
    avatarInitials: 'BW',
    status: 'new',
    lastModified: '2026-05-15',
    programId: undefined,
    assignedEmployeeIds: ['emp2'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 6,
    clinicId: 'clinic1',
    metrics: { age: 28, sexAssignedAtBirth: 'Female', height: "5'7\"", weight: '155 lbs', handDominance: 'Left' },
    injuryHistory: {
      mechanism: 'Stress urinary incontinence onset with return to running',
      dateOfOnset: 'February 2026',
      surgeryType: 'N/A',
      surgeryDate: 'N/A',
      symptomEvolution: 'Leakage with running, jumping jacks, and heavy lifting. No urgency component.',
      functionalMobility: 'Fully independent. Trains 4–5x/week.',
      management: 'Referral from sports medicine physician.',
      homeEquipment: 'None',
    },
    pmhx: { previousEpisode: 'N/A', pmhx: 'None', previousTreatments: 'None', medicationList: 'None', exams: 'Sports med clearance March 2026' },
    sohx: { job: 'Personal trainer', hobbies: 'Running, CrossFit', socialEnvironment: 'Lives with roommates', physicalEnvironment: 'Apartment, 4th floor elevator', clientGoals: 'Run a half marathon without leakage; return to CrossFit fully' },
    lifestyle: { otherConditions: 'None', diet: 'High protein, balanced', exercise: 'CrossFit 4x/wk, running 3x/wk', smoker: 'Non-smoker', alcohol: 'Social, weekends' },
    medicalHistory: { otherConditions: 'None', attachments: [] },
    emergencyContact: { firstName: 'Carol', lastName: 'Walters', phone: '312-555-0408', email: 'carol.walters@email.com', address: '50 Oak Ave, Chicago, IL', relationship: 'Parent' },
    documents: [
      { documentId: 'doc1', submittedAt: '2026-05-15', fieldValues: { f1: '1998-06-20', f2: 'Stress urinary incontinence with exercise', f3: '3 months', f4: 'No', f5: 'None', f6: 'None', f7: 'Run a half marathon and CrossFit without leakage' } },
    ],
  },
  {
    id: 'pat5',
    firstName: 'Diane',
    lastName: 'Morrison',
    email: 'diane.morrison@email.com',
    phone: '617-555-0509',
    address: '77 Beacon St, Boston, MA 02108',
    location: 'New York City, NY',
    avatarInitials: 'DM',
    status: 'active',
    lastModified: '2026-04-30',
    programId: 'prog2',
    assignedEmployeeIds: ['emp3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 8,
    clinicId: 'clinic1',
    metrics: { age: 63, sexAssignedAtBirth: 'Female', height: "5'2\"", weight: '175 lbs', handDominance: 'Right' },
    injuryHistory: {
      mechanism: 'Pelvic organ prolapse (cystocele Grade II)',
      dateOfOnset: 'October 2025',
      surgeryType: 'N/A',
      surgeryDate: 'N/A',
      symptomEvolution: 'Pelvic pressure and heaviness worsening throughout the day. Improved with lying down.',
      functionalMobility: 'Independent. Reduced activity due to symptoms.',
      management: 'Conservative management — pelvic floor PT, pessary trial.',
      homeEquipment: 'Pessary (fitted by urogynecologist)',
    },
    pmhx: { previousEpisode: 'Rectocele repair 2015', pmhx: 'Osteoporosis, hypertension', previousTreatments: 'Rectocele repair, HRT', medicationList: 'Alendronate 70mg weekly, Amlodipine 5mg daily, Vagifem 10mcg', exams: 'Pelvic floor ultrasound Nov 2025' },
    sohx: { job: 'Retired librarian', hobbies: 'Gardening, book club', socialEnvironment: 'Lives alone, adult son nearby', physicalEnvironment: '1-storey home, no barriers', clientGoals: 'Manage prolapse symptoms, avoid surgery, continue gardening' },
    lifestyle: { otherConditions: 'Osteoporosis, hypertension', diet: 'Calcium-rich diet', exercise: 'Walking 20 min/day', smoker: 'Non-smoker', alcohol: 'Rare' },
    medicalHistory: { otherConditions: 'Osteoporosis, hypertension, rectocele repair 2015', attachments: [] },
    emergencyContact: { firstName: 'Tom', lastName: 'Morrison', phone: '617-555-0510', email: 'tom.morrison@email.com', address: '77 Beacon St, Boston, MA', relationship: 'Son' },
    documents: [
      { documentId: 'doc1', submittedAt: '2025-11-01', fieldValues: { f1: '1963-01-14', f2: 'Pelvic organ prolapse – cystocele', f3: '6 months', f4: 'Yes – rectocele repair 2015', f5: 'Alendronate, Amlodipine, Vagifem', f6: 'Osteoporosis, hypertension, rectocele repair', f7: 'Manage symptoms and avoid further surgery' } },
    ],
  },
  {
    id: 'pat6',
    firstName: 'Laura',
    lastName: 'Finch',
    email: 'laura.finch@email.com',
    phone: '514-555-0611',
    address: '1000 Rue De La Gauchetière, Montréal, QC H3B 4W5',
    location: 'New York City, NY',
    avatarInitials: 'LF',
    status: 'active',
    lastModified: '2026-05-12',
    programId: 'prog1',
    assignedEmployeeIds: ['emp3'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 12,
    clinicId: 'clinic1',
    metrics: { age: 38, sexAssignedAtBirth: 'Female', height: "5'6\"", weight: '148 lbs', handDominance: 'Right' },
    injuryHistory: {
      mechanism: 'Postpartum – emergency C-section following 18hr labour',
      dateOfOnset: 'January 2026',
      surgeryType: 'Emergency C-section',
      surgeryDate: 'January 14, 2026',
      symptomEvolution: 'Abdominal scar sensitivity, diastasis recti (2.5cm gap at navel), mild urinary urgency.',
      functionalMobility: 'Independent. Cleared for light activity at 8 weeks.',
      management: 'Scar tissue mobilization, diastasis rehab, pelvic floor strengthening.',
      homeEquipment: 'Yoga mat, supportive abdominal binder',
    },
    pmhx: { previousEpisode: 'N/A', pmhx: 'None', previousTreatments: 'None', medicationList: 'Iron supplements', exams: 'OB clearance March 2026' },
    sohx: { job: 'Nurse (maternity leave)', hobbies: 'Hiking, photography', socialEnvironment: 'Lives with partner and infant', physicalEnvironment: '2nd floor condo, elevator', clientGoals: 'Close diastasis, reduce scar sensitivity, return to hiking' },
    lifestyle: { otherConditions: 'None', diet: 'Balanced, breastfeeding', exercise: 'Walking, light stretching', smoker: 'Non-smoker', alcohol: 'None (breastfeeding)' },
    medicalHistory: { otherConditions: 'None', attachments: [] },
    emergencyContact: { firstName: 'Marc', lastName: 'Finch', phone: '514-555-0612', email: 'marc.finch@email.com', address: '1000 Rue De La Gauchetière, Montréal, QC', relationship: 'Spouse' },
    documents: [
      { documentId: 'doc1', submittedAt: '2026-03-01', fieldValues: { f1: '1988-04-22', f2: 'Diastasis recti, scar tissue, urinary urgency', f3: '2 months post-op', f4: 'No', f5: 'Iron supplements', f6: 'Emergency C-section Jan 2026', f7: 'Restore core function, reduce scar sensitivity' } },
    ],
  },
  {
    id: 'pat7',
    firstName: 'Natalie',
    lastName: 'Brooks',
    email: 'natalie.brooks@email.com',
    phone: '778-555-0712',
    address: '2345 Oak St, Vancouver, BC V6H 2L2',
    location: 'Vancouver, BC',
    avatarInitials: 'NB',
    status: 'inactive',
    lastModified: '2025-11-14',
    programId: undefined,
    assignedEmployeeIds: [],
    clinicId: 'clinic1',
    archived: true,
    sessionsPerWeek: 1,
    totalSessions: 8,
    metrics: { age: 45, sexAssignedAtBirth: 'Female', height: "5'5\"", weight: '158 lbs', handDominance: 'Right' },
    injuryHistory: { mechanism: 'Pelvic girdle pain following second pregnancy', dateOfOnset: 'March 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Resolved following 8 sessions of physiotherapy. Patient discharged with home program.', functionalMobility: 'Independent, returned to full activity.', management: 'Completed course of pelvic floor PT.', homeEquipment: 'Resistance bands, yoga mat' },
    pmhx: { previousEpisode: 'Pelvic girdle pain during first pregnancy (2020)', pmhx: 'None significant', previousTreatments: 'Physio during first pregnancy', medicationList: 'None', exams: 'OB clearance March 2025' },
    sohx: { job: 'Nurse practitioner', hobbies: 'Swimming, hiking', socialEnvironment: 'Married with 2 children', physicalEnvironment: 'House with stairs', clientGoals: 'Return to hiking and swimming pain-free' },
    lifestyle: { otherConditions: 'None', diet: 'Balanced', exercise: 'Swimming, walking', smoker: 'Non-smoker', alcohol: 'Occasional' },
    medicalHistory: { otherConditions: 'None', attachments: [] },
    emergencyContact: { firstName: 'Dan', lastName: 'Brooks', phone: '778-555-0713', email: 'dan.brooks@email.com', address: '2345 Oak St, Vancouver, BC', relationship: 'Spouse' },
    documents: [],
  },
  {
    id: 'pat8',
    firstName: 'Isabelle',
    lastName: 'Martin (PDF)',
    email: 'isabelle.martin@email.com',
    phone: '',
    address: '',
    location: 'Vancouver, BC',
    avatarInitials: 'IM',
    status: 'new',
    lastModified: '2026-06-01',
    programId: undefined,
    assignedEmployeeIds: ['emp_van3'],
    clinicId: 'clinic1',
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 0,
    documents: [],
  },
  // ── Vancouver new patients ──
  {
    id: 'pat_van5',
    firstName: 'Amy',
    lastName: 'Park (comments)',
    email: 'amy.park@email.com',
    phone: '604-555-0501',
    address: '1200 Granville St, Vancouver, BC V6Z 1M3',
    location: 'Vancouver, BC',
    avatarInitials: 'AP',
    status: 'active',
    lastModified: '2026-05-08',
    programId: undefined,
    assignedEmployeeIds: ['emp2'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 5,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Postpartum incontinence – 10 weeks post vaginal delivery', dateOfOnset: 'March 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'SUI with coughing and sneezing.', functionalMobility: 'Independent.', management: 'Referral from midwife.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_van6',
    firstName: 'Rachel',
    lastName: 'Singh',
    email: 'rachel.singh@email.com',
    phone: '604-555-0602',
    address: '350 Robson St, Vancouver, BC V6B 2B4',
    location: 'Vancouver, BC',
    avatarInitials: 'RS',
    status: 'active',
    lastModified: '2026-04-28',
    programId: 'prog3',
    assignedEmployeeIds: ['emp2'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 9,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Chronic pelvic pain following laparoscopy for endometriosis', dateOfOnset: 'November 2025', surgeryType: 'Diagnostic laparoscopy', surgeryDate: 'October 2025', symptomEvolution: 'Deep pelvic aching and dyspareunia persisting post-op.', functionalMobility: 'Independent, avoids prolonged sitting.', management: 'Pelvic floor PT, pain neuroscience education.', homeEquipment: 'Foam roller, heat pack' },
    documents: [],
  },
  {
    id: 'pat_van7',
    firstName: 'Emma',
    lastName: 'Kowalski',
    email: 'emma.kowalski@email.com',
    phone: '778-555-0703',
    address: '88 W Hastings St, Vancouver, BC V6B 1G6',
    location: 'Vancouver, BC',
    avatarInitials: 'EK',
    status: 'new',
    lastModified: '2026-05-30',
    programId: undefined,
    assignedEmployeeIds: ['emp_van3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 0,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Urge urinary incontinence – onset gradual over 18 months', dateOfOnset: 'January 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Urgency episodes 5–6x/day, nocturia 2x.', functionalMobility: 'Independent.', management: 'GP referral.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_van8',
    firstName: 'Chloe',
    lastName: 'Tanaka',
    email: 'chloe.tanaka@email.com',
    phone: '604-555-0804',
    address: '2150 Yew St, Vancouver, BC V6K 3J7',
    location: 'Vancouver, BC',
    avatarInitials: 'CT',
    status: 'active',
    lastModified: '2026-05-14',
    programId: 'prog2',
    assignedEmployeeIds: ['emp_van3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 6,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Stress urinary incontinence with return to marathon training', dateOfOnset: 'February 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Leakage with running >5 km. No rest symptoms.', functionalMobility: 'Highly active.', management: 'Sports physio referral.', homeEquipment: 'Resistance bands' },
    documents: [],
  },
  {
    id: 'pat_van9',
    firstName: 'Mei',
    lastName: 'Xu',
    email: 'mei.xu@email.com',
    phone: '604-555-0905',
    address: '560 Davie St, Vancouver, BC V6B 2G6',
    location: 'Vancouver, BC',
    avatarInitials: 'MX',
    status: 'active',
    lastModified: '2026-05-03',
    programId: 'prog1',
    assignedEmployeeIds: ['emp_van3'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 11,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Postpartum – emergency C-section, diastasis recti 3 cm', dateOfOnset: 'December 2025', surgeryType: 'Emergency C-section', surgeryDate: 'November 2025', symptomEvolution: 'Abdominal weakness, scar tenderness, mild SUI.', functionalMobility: 'Independent. Carrying infant regularly.', management: 'Pelvic floor PT, scar mobilisation.', homeEquipment: 'Supportive binder, yoga mat' },
    documents: [],
  },
  // ── New York City new patients ──
  {
    id: 'pat_nyc3',
    firstName: 'Sophie',
    lastName: 'Adams',
    email: 'sophie.adams@email.com',
    phone: '212-555-1003',
    address: '310 W 72nd St, New York, NY 10023',
    location: 'New York City, NY',
    avatarInitials: 'SA',
    status: 'active',
    lastModified: '2026-05-19',
    programId: 'prog1',
    assignedEmployeeIds: ['emp4'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 7,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Postpartum pelvic floor dysfunction – 8 weeks post twin vaginal delivery', dateOfOnset: 'March 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Mixed incontinence, pelvic heaviness, perineal discomfort.', functionalMobility: 'Independent.', management: 'OB referral.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_nyc4',
    firstName: 'Keisha',
    lastName: 'Williams',
    email: 'keisha.williams@email.com',
    phone: '347-555-1104',
    address: '650 Lenox Ave, New York, NY 10037',
    location: 'New York City, NY',
    avatarInitials: 'KW',
    status: 'active',
    lastModified: '2026-05-11',
    programId: 'prog2',
    assignedEmployeeIds: ['emp4'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 14,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Pelvic organ prolapse (rectocele Grade I) post-menopause', dateOfOnset: 'August 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Pelvic pressure, incomplete emptying, mild constipation.', functionalMobility: 'Independent.', management: 'Urogynecology referral, conservative PT.', homeEquipment: 'Pessary (fitted)' },
    documents: [],
  },
  {
    id: 'pat_nyc5',
    firstName: 'Jennifer',
    lastName: 'Hayes',
    email: 'jennifer.hayes@email.com',
    phone: '718-555-1205',
    address: '92 Flatbush Ave, Brooklyn, NY 11217',
    location: 'New York City, NY',
    avatarInitials: 'JH',
    status: 'active',
    lastModified: '2026-04-25',
    programId: 'prog3',
    assignedEmployeeIds: ['emp4'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 5,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Vulvodynia – generalised, provoked, onset 2 years ago', dateOfOnset: 'June 2024', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Burning, stinging with touch and prolonged sitting. Sleep disruption.', functionalMobility: 'Independent, activity limited by pain.', management: 'Gynaecology referral, low-dose topical therapy.', homeEquipment: 'Cushion, ice packs' },
    documents: [],
  },
  {
    id: 'pat_nyc6',
    firstName: 'Aisha',
    lastName: 'Thompson',
    email: 'aisha.thompson@email.com',
    phone: '646-555-1306',
    address: '215 E 96th St, New York, NY 10128',
    location: 'New York City, NY',
    avatarInitials: 'AT',
    status: 'new',
    lastModified: '2026-05-28',
    programId: undefined,
    assignedEmployeeIds: ['emp4'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 0,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Stress urinary incontinence onset post-partum – 4 months after C-section', dateOfOnset: 'February 2026', surgeryType: 'C-section', surgeryDate: 'October 2025', symptomEvolution: 'Leakage with coughing, sneezing, lifting infant.', functionalMobility: 'Independent.', management: 'OB referral.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_nyc7',
    firstName: 'Maria',
    lastName: 'Gonzalez',
    email: 'maria.gonzalez@email.com',
    phone: '917-555-1407',
    address: '77 Jackson Ave, Long Island City, NY 11101',
    location: 'New York City, NY',
    avatarInitials: 'MG',
    status: 'active',
    lastModified: '2026-05-06',
    programId: 'prog2',
    assignedEmployeeIds: ['emp_nyc3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 8,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Chronic pelvic pain – interstitial cystitis diagnosis', dateOfOnset: 'January 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Bladder pain, urinary frequency 15–20x/day, dyspareunia.', functionalMobility: 'Independent, activity restricted.', management: 'Urology and PT co-management.', homeEquipment: 'Heat pad, TENS unit' },
    documents: [],
  },
  {
    id: 'pat_nyc8',
    firstName: 'Tanya',
    lastName: 'Ross',
    email: 'tanya.ross@email.com',
    phone: '212-555-1508',
    address: '445 W 23rd St, New York, NY 10011',
    location: 'New York City, NY',
    avatarInitials: 'TR',
    status: 'active',
    lastModified: '2026-04-17',
    programId: 'prog1',
    assignedEmployeeIds: ['emp_nyc3'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 12,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Post-hysterectomy pelvic floor rehabilitation', dateOfOnset: 'January 2026', surgeryType: 'Total laparoscopic hysterectomy', surgeryDate: 'December 2025', symptomEvolution: 'Urinary urgency, pelvic heaviness, mild SUI post-op.', functionalMobility: 'Independent, returned to desk work at 6 weeks.', management: 'Surgeon referral post-op.', homeEquipment: 'Yoga mat' },
    documents: [],
  },
  {
    id: 'pat_nyc9',
    firstName: 'Claire',
    lastName: 'Burke',
    email: 'claire.burke@email.com',
    phone: '646-555-1609',
    address: '1 E 81st St, New York, NY 10028',
    location: 'New York City, NY',
    avatarInitials: 'CB',
    status: 'active',
    lastModified: '2026-05-22',
    programId: 'prog3',
    assignedEmployeeIds: ['emp_nyc3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 4,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Diastasis recti and pelvic floor weakness – 6 months postpartum', dateOfOnset: 'November 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Core instability, low back pain, occasional leakage with exercise.', functionalMobility: 'Independent, returned to light exercise.', management: 'OB referral.', homeEquipment: 'Resistance bands, foam roller' },
    documents: [],
  },
  {
    id: 'pat_nyc10',
    firstName: 'Nina',
    lastName: 'Patel',
    email: 'nina.patel@email.com',
    phone: '718-555-1710',
    address: '305 E 24th St, New York, NY 10010',
    location: 'New York City, NY',
    avatarInitials: 'NP',
    status: 'new',
    lastModified: '2026-05-29',
    programId: undefined,
    assignedEmployeeIds: ['emp_nyc3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 0,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Pelvic girdle pain in third trimester of first pregnancy', dateOfOnset: 'April 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Symphysis pubis pain, SI joint pain, difficulty walking.', functionalMobility: 'Limited mobility, using crutches intermittently.', management: 'OB referral, urgent PT.', homeEquipment: 'Pelvic support belt' },
    documents: [],
  },
  // ── Utrecht new patients ──
  {
    id: 'pat_uth1',
    firstName: 'Anna',
    lastName: 'de Vries',
    email: 'anna.devries@email.com',
    phone: '+31 6 5501 1001',
    address: 'Oudegracht 44, 3511 AR Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'AV',
    status: 'active',
    lastModified: '2026-05-16',
    programId: 'prog2',
    assignedEmployeeIds: ['emp_uth1'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 6,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Pelvic organ prolapse (cystocele Grade II) post-menopause', dateOfOnset: 'September 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Pelvic heaviness, urgency, nocturia 2x.', functionalMobility: 'Independent, reduced walking distance.', management: 'Huisarts referral, pessary fitting.', homeEquipment: 'Pessary' },
    documents: [],
  },
  {
    id: 'pat_uth2',
    firstName: 'Marta',
    lastName: 'Jensen',
    email: 'marta.jensen@email.com',
    phone: '+31 6 5502 1002',
    address: 'Maliebaan 12, 3581 CN Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'MJ',
    status: 'active',
    lastModified: '2026-05-09',
    programId: 'prog1',
    assignedEmployeeIds: ['emp_uth1'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 10,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Postpartum – vaginal delivery with 3rd degree tear', dateOfOnset: 'February 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Perineal pain, SUI, reduced sexual function.', functionalMobility: 'Independent, returning to normal activity.', management: 'Kraamzorg referral to bekkenbodem PT.', homeEquipment: 'Yoga mat' },
    documents: [],
  },
  {
    id: 'pat_uth3',
    firstName: 'Emma',
    lastName: 'van den Berg',
    email: 'emma.vandenberg@email.com',
    phone: '+31 6 5503 1003',
    address: 'Lange Nieuwstraat 20, 3512 PB Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'EB',
    status: 'active',
    lastModified: '2026-05-21',
    programId: 'prog3',
    assignedEmployeeIds: ['emp_uth2'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 7,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Stress urinary incontinence with trampolining and CrossFit', dateOfOnset: 'October 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Leakage with jumping and heavy lifts. No rest symptoms.', functionalMobility: 'Very active.', management: 'Huisarts referral.', homeEquipment: 'Resistance bands' },
    documents: [],
  },
  {
    id: 'pat_uth4',
    firstName: 'Sarah',
    lastName: 'Bakker',
    email: 'sarah.bakker@email.com',
    phone: '+31 6 5504 1004',
    address: 'Biltstraat 55, 3572 AK Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'SB',
    status: 'active',
    lastModified: '2026-04-30',
    programId: 'prog2',
    assignedEmployeeIds: ['emp_uth2'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 13,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Chronic pelvic pain – vulvodynia and vestibulodynia', dateOfOnset: 'March 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Provoked pain, dyspareunia, psychological impact noted.', functionalMobility: 'Independent, work affected.', management: 'Psychosomatic physiotherapy co-management.', homeEquipment: 'Dilator set, vibrator (therapeutic)' },
    documents: [],
  },
  {
    id: 'pat_uth5',
    firstName: 'Lisa',
    lastName: 'de Boer',
    email: 'lisa.deboer@email.com',
    phone: '+31 6 5505 1005',
    address: 'Wittevrouwenstraat 8, 3512 CK Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'LB',
    status: 'active',
    lastModified: '2026-05-04',
    programId: 'prog1',
    assignedEmployeeIds: ['emp_uth2'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 4,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Postpartum – elective C-section, diastasis recti 2 cm', dateOfOnset: 'January 2026', surgeryType: 'Elective C-section', surgeryDate: 'December 2025', symptomEvolution: 'Scar sensitivity, abdominal weakness, mild urgency.', functionalMobility: 'Independent.', management: 'Kraamzorg referral.', homeEquipment: 'Abdominal binder, yoga mat' },
    documents: [],
  },
  {
    id: 'pat_uth6',
    firstName: 'Julia',
    lastName: 'Smits',
    email: 'julia.smits@email.com',
    phone: '+31 6 5506 1006',
    address: 'Hoogt 14, 3512 GW Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'JS',
    status: 'new',
    lastModified: '2026-05-27',
    programId: undefined,
    assignedEmployeeIds: ['emp_uth2'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 0,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Urge urinary incontinence – onset following UTI 6 months ago', dateOfOnset: 'December 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Urgency, frequency 10–12x/day, bladder diary underway.', functionalMobility: 'Independent.', management: 'Huisarts referral.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_uth7',
    firstName: 'Petra',
    lastName: 'Hoffman',
    email: 'petra.hoffman@email.com',
    phone: '+31 6 5507 1007',
    address: 'Korte Minrebroederstraat 2, 3512 GD Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'PH',
    status: 'active',
    lastModified: '2026-05-13',
    programId: 'prog2',
    assignedEmployeeIds: ['emp_uth3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 5,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Mixed urinary incontinence – perimenopausal onset', dateOfOnset: 'July 2025', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Urgency, stress leakage, disrupted sleep.', functionalMobility: 'Independent.', management: 'Gynaecologist referral.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_uth8',
    firstName: 'Inge',
    lastName: 'Visser',
    email: 'inge.visser@email.com',
    phone: '+31 6 5508 1008',
    address: 'Lucasbolwerk 3, 3512 EG Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'IV',
    status: 'active',
    lastModified: '2026-04-22',
    programId: 'prog3',
    assignedEmployeeIds: ['emp_uth3'],
    archived: false,
    sessionsPerWeek: 2,
    totalSessions: 16,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Post-surgical pelvic floor rehab after prolapse repair (sacrocolpopexy)', dateOfOnset: 'November 2025', surgeryType: 'Laparoscopic sacrocolpopexy', surgeryDate: 'October 2025', symptomEvolution: 'Post-op urinary retention resolved. Now working on pelvic floor reconditioning.', functionalMobility: 'Independent, light activity only.', management: 'Urogynaecologist referral.', homeEquipment: 'Yoga mat, pelvic wand' },
    documents: [],
  },
  {
    id: 'pat_uth9',
    firstName: 'Noor',
    lastName: 'el Amrani',
    email: 'noor.elamrani@email.com',
    phone: '+31 6 5509 1009',
    address: 'Vleutenseweg 100, 3532 AD Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'NA',
    status: 'new',
    lastModified: '2026-05-31',
    programId: undefined,
    assignedEmployeeIds: ['emp_uth3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 0,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Postpartum – vaginal delivery with episiotomy, 6 weeks post', dateOfOnset: 'April 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'Perineal scar pain, SUI with coughing, pelvic heaviness.', functionalMobility: 'Independent.', management: 'Kraamzorg and huisarts referral.', homeEquipment: 'None' },
    documents: [],
  },
  {
    id: 'pat_uth10',
    firstName: 'Hanna',
    lastName: 'Müller',
    email: 'hanna.muller@email.com',
    phone: '+31 6 5510 1010',
    address: 'Croeselaan 14, 3521 CB Utrecht, Netherlands',
    location: 'Utrecht, Netherlands',
    avatarInitials: 'HM',
    status: 'active',
    lastModified: '2026-05-07',
    programId: 'prog1',
    assignedEmployeeIds: ['emp_uth3'],
    archived: false,
    sessionsPerWeek: 1,
    totalSessions: 3,
    clinicId: 'clinic1',
    injuryHistory: { mechanism: 'Pelvic girdle pain – onset mid-pregnancy, now 32 weeks', dateOfOnset: 'March 2026', surgeryType: 'N/A', surgeryDate: 'N/A', symptomEvolution: 'SI joint and pubic symphysis pain, worsening with walking and stairs.', functionalMobility: 'Limited, using pelvic support belt.', management: 'Verloskunde referral.', homeEquipment: 'Pelvic support belt, pillow wedge' },
    documents: [],
  },
];

export const mockChartSessions: Record<string, ChartSession[]> = {
  pat1: [
    {
      id: 'cs1-intake',
      patientId: 'pat1',
      date: '2026-04-15',
      isIntakeSession: true,
      summary: 'Initial intake assessment. Discussed postpartum symptoms, pelvic floor anatomy education. Performed internal assessment — mild hypotonicity noted. Established baseline.',
      painLevel: 'Low Pain',
      adherenceLevel: undefined,
      improvementLevel: undefined,
      exercisesPerDay: 3,
      soapie: {
        subjective: 'Pt c/o SUI × 6/52 p/o SVD — urinary leakage ↑ c/ cough/sneeze. NPRS 2/10 (discomfort). No urgency. No pelvic pain. Motivated to begin Rx.',
        objective: 'External: mild perineal scarring, healing WNL. Internal: levator ani 2/5 B/L; moderate hypotonicity; endurance hold 3 sec; quick flicks 5/10.',
        assessment: 'Postpartum PF hypotonicity → SUI. No red flags. ↑ rehab potential.',
        plan: 'Initiate PFMT (3 exercises). Pt ed: PF anatomy, bladder habits, hydration. Rx: 6 sessions × 1×/wk.',
        intervention: 'Manual Rx: gentle CT mobilization. HEP: diaphragmatic breathing, TA activation, sustained Kegel 5 sec × 10 reps. Verbal + visual anatomy ed. Handout provided.',
        evaluation: 'Pt demonstrated correct Kegel technique by EOSession ✓. Good comprehension of anatomy. NPRS 2/10 — unchanged; expected at this stage.',
        recommendations: 'HEP 2×/day. Avoid ↑ impact activity × 6/52 p/o. F/u w/ OB/GYN at 6-wk postpartum appt. ↑ hydration → 2L/day; ↓ caffeine.',
      },
    },
    {
      id: 'cs1-2',
      patientId: 'pat1',
      date: '2026-04-29',
      isIntakeSession: false,
      summary: 'Second session. Patient completing exercises 5/7 days. Slight improvement in leakage episodes. Progressed program to include hip bridge.',
      painLevel: 'Low Pain',
      adherenceLevel: 'Moderate Adherence',
      improvementLevel: 'Some Improvement',
      exercisesPerDay: 4,
      soapie: {
        subjective: 'Pt reports ↓ leakage episodes × ~40% (↓ from daily → ~3–4/wk). HEP adherence: 5/7 days (forgetting evenings). NPRS 1/10.',
        objective: 'Levator ani 2–3/5 B/L (↑ from 2/5). ↑ motor coordination noted. Endurance hold: 5 sec × 10.',
        assessment: 'Good early Rx response. Primary barrier: adherence (evening routine). Prognosis: ↑.',
        plan: '↑ HEP → 4 exercises. Address adherence via habit stacking. Reassess in 2/52.',
        intervention: 'Added hip bridge 3×10. Habit stacking — linked HEP to AM + PM infant feeding schedule.',
        evaluation: 'Pt engaged c/ habit planning ✓. Confident c/ new exercise. Technique ✓.',
        recommendations: 'Link HEP to AM + PM feeds. Journal leakage episodes. Return 2/52.',
      },
    },
    {
      id: 'cs1-3',
      patientId: 'pat1',
      date: '2026-05-13',
      isIntakeSession: false,
      summary: 'Third session. Strong adherence this week. Leakage reduced significantly. Discussing return to yoga timeline.',
      painLevel: 'No Pain',
      adherenceLevel: 'High Adherence',
      improvementLevel: 'Significant Improvement',
      exercisesPerDay: 4,
      soapie: {
        subjective: 'Pt reports ↓ SUI → 1–2 episodes/wk (↓ from daily at intake). HEP adherence: 7/7 days. NPRS 0/10. No urgency. Returning to yoga next week.',
        objective: 'Levator ani 3/5 B/L (↑ from 2/5). Coordination ↑↑. Endurance hold: 8 sec × 10.',
        assessment: 'Excellent Rx response. Ready for functional progressions. On track for D/C in 2–3 sessions.',
        plan: '↑ → functional movements (BW squat c/ PF cue). Discuss RTS yoga timeline. Target D/C: 2/52.',
        intervention: 'Added BW squat c/ PF cue 3×10. Pt ed: impact loading progression; ↑ IAP management. Handout provided.',
        evaluation: 'Excellent session — pt very motivated. Technique ✓ all exercises. NPRS 0/10. Target RTS yoga in 4/52.',
        recommendations: 'Begin low-impact yoga per handout (next week). Avoid running × 4/52. To GP (Dr. Patel): pt progressing well; anticipate D/C in 2 sessions.',
      },
    },
  ],
  pat2: [
    {
      id: 'cs2-intake',
      patientId: 'pat2',
      date: '2026-03-20',
      isIntakeSession: true,
      summary: 'Intake session for mixed incontinence. Bladder diary reviewed — 8 voids/day, 2 nocturnal. Assessment revealed weak pelvic floor with poor coordination.',
      painLevel: 'No Pain',
      exercisesPerDay: 0,
      soapie: {
        subjective: 'Pt c/o MUI: SUI (↑ c/ cough/sneeze/jumping) + UUI (urgency 3–4×/day). Bladder diary: 8 voids/day, 2 nocturnal. NPRS 0/10. ↓ QoL — avoids tennis.',
        objective: 'Internal: levator ani 1–2/5; significant motor control deficit; poor coordination; no guarding.',
        assessment: 'MUI: stress + urge components. ↓ PF strength + motor control. STG: ↑ awareness; ↓ urgency episodes.',
        plan: 'Prioritize motor control + coordination before ↑ strength. Bladder retraining protocol. Rx: 8 sessions × 1×/wk.',
        intervention: 'PF awareness, diaphragmatic breathing, quick flick Kegels 10×. Bladder retraining ed (delay techniques). Handout provided.',
        evaluation: '↓ Difficulty isolating PF by EOSession ✓. Good comprehension. NPRS 0/10.',
        recommendations: 'Bladder diary × 2/52 (template provided). ↓ caffeine + carbonated beverages. HEP 3×/day. Avoid urgency suppression strategies.',
      },
    },
    {
      id: 'cs2-2',
      patientId: 'pat2',
      date: '2026-04-03',
      isIntakeSession: false,
      summary: 'Updated program, brainstormed adherence strategies. Patient finding it hard to remember exercises during busy workdays.',
      painLevel: 'No Pain',
      adherenceLevel: 'Low Adherence',
      improvementLevel: 'No Improvement',
      exercisesPerDay: 4,
      soapie: {
        subjective: 'HEP adherence: 2–3/7 days (busy work schedule). No Sx Δ. NPRS 0/10. Pt frustrated c/ lack of progress.',
        objective: 'Levator ani: unchanged 2/5. Coordination ↑ slightly.',
        assessment: 'Adherence barrier → primary obstacle; no clinical Δ expected at 2 sessions. Prognosis ↑ if adherence ↑.',
        plan: '↓ HEP complexity → 3 key exercises. Set phone reminders. Reassess 2/52.',
        intervention: '↓ HEP → 3 exercises. Phone reminders set during session. Motivational interviewing.',
        evaluation: '↑ Confidence c/ simplified plan. Pt optimistic. NPRS 0/10.',
        recommendations: 'Continue simplified HEP c/ phone reminders. ↓ fluids after 7 PM. Reassess 2/52 — escalate to urogynecology if no ↑ in 4 sessions.',
      },
    },
    {
      id: 'cs2-3',
      patientId: 'pat2',
      date: '2026-04-17',
      isIntakeSession: false,
      summary: 'Confidence of patient improved. Increased adherence this week with reminder system. Some improvement in urgency.',
      painLevel: 'No Pain',
      adherenceLevel: 'High Adherence',
      improvementLevel: 'Some Improvement',
      exercisesPerDay: 4,
      soapie: {
        subjective: 'HEP adherence: 6/7 days (↑↑ c/ reminder system). ↓ urgency → 1–2 episodes/day (↓ from 3–4/day). SUI: unchanged. NPRS 0/10.',
        objective: 'Levator ani 2–3/5 (↑). ↑ coordination. Stress leakage: unchanged on cough test.',
        assessment: '↑ urgency component. SUI: primary target remaining. Adherence ↑↑ c/ reminder system.',
        plan: '↑ → sustained holds (10 sec) + functional squat. Target tennis RTS in 6/52.',
        intervention: 'Added sustained Kegel 10 sec × 10 reps. Introduced BW squat c/ PF cue 3×10.',
        evaluation: '↑ Strong session. Pt very motivated. Technique ✓. Target RTS tennis in 6/52.',
        recommendations: '↑ → sustained holds + functional squat at home. Monitor RTS tennis readiness at next session. Continue bladder diary.',
      },
    },
  ],
  pat3: [
    {
      id: 'cs3-intake',
      patientId: 'pat3',
      date: '2026-01-28',
      isIntakeSession: true,
      summary: 'Post-surgical intake for pelvic pain following hysterectomy. Hypertonic pelvic floor identified. Pain education session provided.',
      painLevel: 'High Pain',
      exercisesPerDay: 3,
      soapie: {
        subjective: 'Pt c/o deep pelvic aching s/p TAH (3 mos). NPRS 5/10 — ↑ c/ sitting > 30 min + sexual activity; ↓ c/ standing + walking. Night pain: occasional.',
        objective: 'Significant PF hypertonicity on internal assessment. Levator ani 3/5 c/ guarding. ↑ tone B/L. ↑ tenderness on palpation.',
        assessment: 's/p TAH → hypertonic PF c/ central sensitization component. STG: ↓ NPRS → 3/10; ↓ hypertonicity.',
        plan: 'Prioritize relaxation + pain ed. NO strengthening until hypertonicity ↓. Rx: 8 sessions × 1×/wk.',
        intervention: 'Pain neuroscience ed. Diaphragmatic breathing 3×10. Cat-cow 3×10. Gentle CT stretching.',
        evaluation: 'Pt responded ✓ to pain ed — visible tension ↓ c/ breathing exercises. NPRS: 5/10 pre → 4/10 post.',
        recommendations: 'Avoid sitting > 30 min — use timer. Moist heat to pelvis PRN. HEP 2×/day. To GP: initiated PT for post-TAH pelvic pain.',
      },
    },
    {
      id: 'cs3-2',
      patientId: 'pat3',
      date: '2026-02-11',
      isIntakeSession: false,
      summary: 'Second session. Good adherence with relaxation program. Pain reducing. Scar tissue mobilization initiated.',
      painLevel: 'Moderate Pain',
      adherenceLevel: 'High Adherence',
      improvementLevel: 'Some Improvement',
      exercisesPerDay: 3,
      soapie: {
        subjective: 'NPRS ↓ 3/10 (↓ from 5/10). ↑ sitting tolerance → 45 min. HEP adherence: 7/7 days. Sexual activity still avoided.',
        objective: '↓ PF hypertonicity on assessment. Scar: mobility restricted superiorly at low abdominal level.',
        assessment: '↑ progress. Scar restriction → contributing to Sx. CT mobility: priority next phase.',
        plan: 'Continue relaxation program. Introduce scar massage (self-technique). Reassess 2/52.',
        intervention: 'Scar tissue mobilization — pt educated on self-massage ✓. Added pelvic tilt 3×10.',
        evaluation: 'Pt comfortable c/ scar massage technique ✓. Optimistic re: progress. NPRS 3/10.',
        recommendations: 'Scar self-massage 2×/day as instructed. HEP as prescribed. F/u c/ GP if NPRS ↑ or returns to baseline.',
      },
    },
  ],
  pat4: [
    {
      id: 'cs4-intake',
      patientId: 'pat4',
      date: '2026-05-15',
      isIntakeSession: true,
      summary: 'Intake session. Athletic patient with SUI during high-impact exercise. No program assigned yet. Baseline assessment completed.',
      painLevel: 'No Pain',
      exercisesPerDay: 0,
      soapie: {
        subjective: 'Pt c/o SUI c/ running + box jumps (gym). NPRS 0/10. No urgency. No pelvic pain. No h/o obstetric or surgical trauma.',
        objective: 'Levator ani 3/5 B/L — good baseline strength. ↓ PF coordination under ↑ load. Quick flicks: 8/10.',
        assessment: 'SUI c/ load-related PF incoordination. ↑ Prognosis — normal baseline strength; motor re-learning is primary target.',
        plan: 'Prescribe foundational program. Focus: PF coordination c/ ↑ activity. Rx: 4 sessions × 1×/wk.',
        intervention: 'Ed: the knack maneuver ✓. Diaphragmatic breathing + TA activation 3×10. PF coordination drill.',
        evaluation: '↑ Motivated; quick learner. Technique ✓ by EOSession. NPRS 0/10.',
        recommendations: 'HEP daily. Practice knack × running + box jumps. Log leakage episodes. Return 2/52 c/ exercise log.',
      },
    },
  ],
  pat5: [
    {
      id: 'cs5-intake',
      patientId: 'pat5',
      date: '2025-11-10',
      isIntakeSession: true,
      summary: 'Intake for pelvic organ prolapse. Grade II cystocele confirmed. Conservative management planned. Pessary already fitted by urogynecologist.',
      painLevel: 'Moderate Pain',
      exercisesPerDay: 5,
      soapie: {
        subjective: 'Pt c/o pelvic pressure + heaviness throughout day (↑ c/ prolonged standing). Pessary (Dr. Nguyen) → partial relief. NPRS 3/10. No SUI.',
        objective: 'POP grade II cystocele (prev urogynecology assessment). PF: 2/5 B/L; ↑ levator hiatus.',
        assessment: '↓ PF strength → ↑ POP Sx. Conservative management: pessary + PFMT. STG: ↓ heaviness; ↑ PF → 3/5.',
        plan: 'PFMT c/ POP precautions. Avoid Valsalva + ↑ IAP activities. Rx: 8 sessions × 1×/wk.',
        intervention: 'Ed: POP mechanics + lifting technique ✓. Initiated gentle PFMT 3×10 (2 sec hold). POP precautions handout provided.',
        evaluation: 'Pt understands conservative Rx approach ✓. Motivated to avoid surgical intervention. NPRS 3/10.',
        recommendations: 'Pessary per urogynecologist protocol (Dr. Nguyen). Avoid lifting > 5 lbs + Valsalva. HEP as prescribed. F/u c/ Dr. Nguyen as scheduled.',
      },
    },
    {
      id: 'cs5-2',
      patientId: 'pat5',
      date: '2025-11-24',
      isIntakeSession: false,
      summary: 'Good adherence. Prolapse symptoms slightly improved, especially in the morning. Progressed exercises.',
      painLevel: 'Low Pain',
      adherenceLevel: 'High Adherence',
      improvementLevel: 'Some Improvement',
      exercisesPerDay: 5,
      soapie: {
        subjective: 'HEP adherence: 7/7 days. ↓ heaviness in AM (↑ by evening — gravity effect expected). NPRS ↓ 2/10 (↓ from 3/10). Pessary comfortable.',
        objective: 'Levator ani 2–3/5 B/L (↑ from 2/5). ↑ endurance noted.',
        assessment: '↑ early Rx response. Gravity effect at EODay: expected — address c/ supine exercises.',
        plan: '↑ program. Add supine exercises for PM routine. Reassess 2/52.',
        intervention: 'Added hip bridge 3×10 + clamshell 3×15 B/L. Supine HEP evening routine established.',
        evaluation: 'Technique ✓ all exercises. ↑ Progressing well. NPRS 2/10.',
        recommendations: 'Continue POP precautions (no ↑ lifting, avoid prolonged standing). Add supine exercise routine (evenings). F/u c/ Dr. Nguyen as scheduled.',
      },
    },
  ],
  pat6: [
    {
      id: 'cs6-intake',
      patientId: 'pat6',
      date: '2026-03-05',
      isIntakeSession: true,
      summary: 'Intake following emergency C-section. Diastasis recti 2.5cm at navel. Scar tenderness. Mild urgency. Pelvic floor assessment within normal limits.',
      painLevel: 'Low Pain',
      exercisesPerDay: 3,
      soapie: {
        subjective: 'Pt c/o s/p emergency LSCS (6/52). Scar: sensitive to touch. ↓ abdominal strength. Mild UUI × 2/day. NPRS 2/10. Querying RTS hiking.',
        objective: 'Diastasis recti: 2.5 cm at umbilicus (↓ tension on linea alba). Scar mobility: ↓ cranially. PF: 3/5 B/L — WNL.',
        assessment: 'Post-LSCS c/ diastasis recti (2.5 cm) + scar restriction. No red flags. PF WNL.',
        plan: 'Scar ed + early mobility. Diastasis rehab program. PFMT for UUI. Rx: 6 sessions × 1×/wk.',
        intervention: 'Scar desensitization Rx. Diaphragmatic breathing + TA activation 3×10. Diastasis precautions ed. Handout provided.',
        evaluation: 'Pt responded ✓. Good understanding of diastasis precautions. NPRS 2/10 post.',
        recommendations: 'Scar desensitization 2×/day. Avoid sit-ups, crunches + loaded flexion. Begin 10–15 min walks this week. F/u c/ OB/GYN at 6-wk check.',
      },
    },
    {
      id: 'cs6-2',
      patientId: 'pat6',
      date: '2026-03-19',
      isIntakeSession: false,
      summary: 'Diastasis improving — now 1.5cm. Scar mobility improving with home massage. Progressed core program.',
      painLevel: 'Low Pain',
      adherenceLevel: 'High Adherence',
      improvementLevel: 'Significant Improvement',
      exercisesPerDay: 4,
      soapie: {
        subjective: 'NPRS ↓ 1/10. Scar: no longer painful to touch. ↑ abdominal strength (subjective). UUI: resolved. HEP adherence: 7/7 days.',
        objective: 'Diastasis ↓ 1.5 cm (↓ from 2.5 cm) — ↑ tension on linea alba ✓. Scar: ↑ mobile all directions. PF: 3–4/5 B/L.',
        assessment: '↑↑ Excellent progress on all fronts. Ready for functional ↑.',
        plan: '↑ → functional movements. Begin RTS hiking discussion. Target RTS: short hikes in 4/52.',
        intervention: 'Added dead bug 3×10. TA activation ↑ → standing. RTS hiking protocol discussed.',
        evaluation: '↑ Strong session. Technique ✓ all exercises. NPRS 1/10. Target RTS short hikes in 4/52.',
        recommendations: 'RTS hiking: begin 15 min flat trail next week; ↑ by 5 min/wk. Continue HEP. To GP: diastasis ↓ to 1.5 cm; scar mobile; cleared for ↑ low-impact activity.',
      },
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    message: 'Margaret Chen has submitted her Intake Form',
    patientId: 'pat1',
    patientName: 'Margaret Chen',
    tab: 'documents',
    timestamp: '2026-05-22T09:15:00',
    read: false,
    type: 'document',
  },
  {
    id: 'n2',
    message: 'Beth Walters has submitted her Insurance Form',
    patientId: 'pat4',
    patientName: 'Beth Walters',
    tab: 'documents',
    timestamp: '2026-05-21T14:30:00',
    read: false,
    type: 'document',
  },
  {
    id: 'n3',
    message: 'Karen Oduya has submitted her Credit Card Authorization',
    patientId: 'pat2',
    patientName: 'Karen Oduya',
    tab: 'documents',
    timestamp: '2026-05-20T11:00:00',
    read: true,
    type: 'document',
  },
  {
    id: 'n4',
    message: 'Laura Finch has submitted her Intake Form',
    patientId: 'pat6',
    patientName: 'Laura Finch',
    tab: 'documents',
    timestamp: '2026-05-19T16:45:00',
    read: true,
    type: 'document',
  },
  {
    id: 'n5',
    message: 'Priya Nair has submitted her Intake Form',
    patientId: 'pat3',
    patientName: 'Priya Nair',
    tab: 'documents',
    timestamp: '2026-05-18T10:20:00',
    read: true,
    type: 'document',
  },
];

import type { PatientComment } from './types';

export const mockPatientComments: Record<string, PatientComment[]> = {
  pat_van5: [
    {
      id: 'c1',
      patientId: 'pat_van5',
      authorId: 'emp1',
      authorName: 'Emily Chen',
      authorInitials: 'EC',
      content: 'Amy mentioned she\'s returning to work next month and is worried about leakage during her commute. Flag for next session — discuss pelvic floor strategies for prolonged sitting and public transit.',
      createdAt: '2026-04-28T14:30:00',
      pinned: true,
    },
    {
      id: 'c2',
      patientId: 'pat_van5',
      authorId: 'emp1',
      authorName: 'Emily Chen',
      authorInitials: 'EC',
      content: 'GP (Dr. Patel) called requesting a progress summary at session 6. Will prepare a brief letter. James — can you pull together session notes by May 20?',
      createdAt: '2026-05-10T09:00:00',
      pinned: true,
    },
    {
      id: 'c3',
      patientId: 'pat_van5',
      authorId: 'emp2',
      authorName: 'James Wilson',
      authorInitials: 'JW',
      content: 'Patient called on April 22 to reschedule Thursday appointment — moved to Friday at 11am. Updated in booking system.',
      createdAt: '2026-04-22T09:15:00',
      pinned: false,
    },
    {
      id: 'c4',
      patientId: 'pat_van5',
      authorId: 'emp2',
      authorName: 'James Wilson',
      authorInitials: 'JW',
      content: 'Sent home exercise reminder email — Amy forgot her Kegel log sheet today. Good energy and motivation during session though.',
      createdAt: '2026-05-02T10:00:00',
      pinned: false,
    },
    {
      id: 'c5',
      patientId: 'pat_van5',
      authorId: 'emp_van3',
      authorName: 'Sophie Kim',
      authorInitials: 'SK',
      content: 'Covered Amy\'s May 1st session while James was away. She reported mild perineal discomfort 2/10 at start of session, resolved fully by the end. No changes to the HEP — continued with James\'s plan.',
      createdAt: '2026-05-01T11:45:00',
      pinned: false,
    },
    {
      id: 'c6',
      patientId: 'pat_van5',
      authorId: 'emp2',
      authorName: 'James Wilson',
      authorInitials: 'JW',
      content: 'Discussed return-to-running timeline. Recommended holding off on jogging for 2 more weeks — will reassess at next session. Patient agreed and seemed relieved to have a clear plan.',
      createdAt: '2026-05-08T15:20:00',
      pinned: false,
    },
    {
      id: 'c7',
      patientId: 'pat_van5',
      authorId: 'emp2',
      authorName: 'James Wilson',
      authorInitials: 'JW',
      content: 'Insurance pre-auth approved for 8 sessions total. Currently at session 5. Will submit extension request after session 8 if discharge criteria not met.',
      createdAt: '2026-05-14T13:30:00',
      pinned: false,
    },
  ],
};
